"""Venue-neutral, paper-only spot arbitrage prototype."""

from packages.arbitrage.engine import (
    ArbitrageConfig,
    ArbitrageEngine,
    executable_vwap,
    scan_opportunities,
    split_symbol,
)
from packages.arbitrage.models import (
    ArbitrageOpportunity,
    BookLevel,
    InsufficientLiquidityError,
    OrderBook,
    PriceLevel,
    Side,
    VWAPResult,
)
from packages.arbitrage.paper import (
    InsufficientBalanceError,
    PaperAccount,
    PaperArbitrageEngine,
    PaperArbitrageExecutor,
    PaperExecution,
    PaperExecutionError,
    PaperExecutor,
    PaperLeg,
    PaperPortfolio,
)
from packages.arbitrage.adapters import (
    BinancePublicAdapter,
    BitgetPublicAdapter,
    BybitPublicAdapter,
    OkxPublicAdapter,
    OrderBookPayloadError,
    PublicVenueAdapter,
    PublicVenueError,
    TickerPayloadError,
)
from packages.arbitrage.service import (
    ArbitragePaperService,
    ScanSettings,
)
from packages.arbitrage.triangular import (
    MarketTicker,
    TriangularConfig,
    TriangularEngine,
    TriangularInsufficientBalanceError,
    TriangularLeg,
    TriangularOpportunity,
    TriangularPaperExecution,
    TriangularPaperExecutionError,
    TriangularPaperExecutor,
    TriangularPaperPortfolio,
    scan_triangular_opportunities,
    select_liquid_tickers,
    ticker_snapshot_key,
)
from packages.arbitrage.triangular_service import (
    TriangularPaperService,
    TriangularScanSettings,
)
from packages.arbitrage.universe import (
    CrossVenueSymbolStats,
    select_cross_venue_universe,
)

__all__ = [
    "ArbitrageConfig",
    "ArbitrageEngine",
    "ArbitrageOpportunity",
    "ArbitragePaperService",
    "BinancePublicAdapter",
    "BitgetPublicAdapter",
    "BookLevel",
    "BybitPublicAdapter",
    "CrossVenueSymbolStats",
    "InsufficientBalanceError",
    "InsufficientLiquidityError",
    "MarketTicker",
    "OrderBook",
    "OrderBookPayloadError",
    "OkxPublicAdapter",
    "PaperAccount",
    "PaperArbitrageEngine",
    "PaperArbitrageExecutor",
    "PaperExecution",
    "PaperExecutionError",
    "PaperExecutor",
    "PaperLeg",
    "PaperPortfolio",
    "PriceLevel",
    "PublicVenueAdapter",
    "PublicVenueError",
    "ScanSettings",
    "Side",
    "TickerPayloadError",
    "TriangularConfig",
    "TriangularEngine",
    "TriangularInsufficientBalanceError",
    "TriangularLeg",
    "TriangularOpportunity",
    "TriangularPaperExecution",
    "TriangularPaperExecutionError",
    "TriangularPaperExecutor",
    "TriangularPaperPortfolio",
    "TriangularPaperService",
    "TriangularScanSettings",
    "VWAPResult",
    "executable_vwap",
    "scan_opportunities",
    "scan_triangular_opportunities",
    "select_liquid_tickers",
    "select_cross_venue_universe",
    "split_symbol",
    "ticker_snapshot_key",
]
